version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/st_backend
permissions:
  - object: /home/ubuntu/st_backend
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforInstall:
    - location: ./before_deploy.sh
      runas: ubuntu
  AfterInstall:
    - location: ./after_deploy.sh
      runas: ubuntu
