version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/stork-analysis
permissions:
  - object: /home/ubuntu/stork-analysis
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforInstall:
    - location: script/before_deploy.sh
      runas: ubuntu
  AfterInstall:
    - location: script/after_deploy.sh
      runas: ubuntu
