name: Build & Deploy
env:
  PROJECT_NAME: stork-analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Create env file
        run: |
          touch .env	
          cat << EOF >> .env	
          ${{ secrets.PROD }}

      - name: Make tar file
        run: tar -cpvzf ./$GITHUB_SHA.tgz ./dist/*
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./$GITHUB_SHA.tgz s3://deploy-archive/$PROJECT_NAME/$GITHUB_SHA.tgz

      # - name: Code Deploy
      #   run: aws deploy create-deployment --application-name bmart5-deploy --file-exists-behavior OVERWRITE --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name bmart5-deploy-group --s3-location bucket=bmart5-s3-bucket,bundleType=tgz,key=$PROJECT_NAME/$GITHUB_SHA.tgz
