name: Build & Deploy
env:
  PROJECT_NAME: st_backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Create env file
        run: |
          touch .env.prod
          cat << EOF >> .env.prod	
          ${{ secrets.PROD }}

      - name: Make tar file
        run: tar -cpvzf ./$GITHUB_SHA.tgz ./dist .env.prod package.json appspec.yml before_deploy.sh after_deploy.sh
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./$GITHUB_SHA.tgz s3://deploy-archive/$PROJECT_NAME/$GITHUB_SHA.tgz

      - name: Code Deploy
        run: aws deploy create-deployment --application-name st_backend --file-exists-behavior OVERWRITE --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name st_backend --s3-location bucket=deploy-archive,bundleType=tgz,key=$PROJECT_NAME/$GITHUB_SHA.tgz
